// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea3_JasonTrejos.Data;

#nullable disable

namespace Tarea3_JasonTrejos.Data.Migrations
{
    [DbContext(typeof(ContextProductos))]
    [Migration("20230420044129_Productos-Migration")]
    partial class ProductosMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarea3_JasonTrejos.Models.Productos", b =>
                {
                    b.Property<int>("id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Producto"));

                    b.Property<DateTime>("fechaCaducidad_Producto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaFabricacion_Producto")
                        .HasColumnType("datetime2");

                    b.Property<string>("lote_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_Proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Producto");

                    b.ToTable("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
